import type { ExecutiveRow } from "../types";

export const getInitialDailySalesData = (
  resolvedProjectId: number,
  resolvedRms: number[]
): ExecutiveRow[] => {
  const firstRmId = resolvedRms[0] || 1;
  const secondRmId = resolvedRms[1] || 2;

    return [
      {
        id: 1,
        name: "Rajesh Sharma",
        projectId: resolvedProjectId,
        projectName: "Planet Green",
        rmId: firstRmId,
        emId: 10,
        newLeads: 14,
        calls: 45,
        followups: 38,
        missed: 2,
        siteVisits: 5,
        advance: 1,
        booking: null,
        payment: null,
        reg: null,
        junk: 4,
      },
      {
        id: 2,
        name: "Anjali Gupta",
        projectId: resolvedProjectId,
        projectName: "Planet Green",
        rmId: firstRmId,
        emId: 11,
        newLeads: 9,
        calls: 32,
        followups: 30,
        missed: 0,
        siteVisits: 3,
        advance: null,
        booking: null,
        payment: null,
        reg: null,
        junk: 1,
      },
      {
        id: 3,
        name: "Vikram Malhotra",
        projectId: resolvedProjectId,
        projectName: "Planet Green",
        rmId: secondRmId,
        emId: 12,
        newLeads: 6,
        calls: 24,
        followups: 18,
        missed: 6,
        siteVisits: 2,
        advance: null,
        booking: 1,
        payment: 1,
        reg: null,
        junk: 2,
      },
      {
        id: 4,
        name: "Sanya Verma",
        projectId: resolvedProjectId,
        projectName: "Planet Green",
        rmId: secondRmId,
        emId: 13,
        newLeads: 11,
        calls: 52,
        followups: 44,
        missed: 0,
        siteVisits: 8,
        advance: null,
        booking: null,
        payment: null,
        reg: 1,
        junk: 7,
      },
    ];
};
