import type { LeadSourceQualityRow } from "../types";

export const getInitialLeadSourceData = (
  resolvedProjectId: number,
  resolvedRms: number[]
): LeadSourceQualityRow[] => {
  const rmCount = resolvedRms.length || 1;

  // We assign realistic projectIds and rmIds so that when filters are toggled, rows filter dynamically.
  return [
    {
      id: 1,
      source: "Instagram Ads",
      projectId: resolvedProjectId,
      rmId: resolvedRms[0] || 1,
      emId: 1,
      count: 1240,
      quantityDistribution: 45,
      conversionRate: 7.2,
      junkRate: 8.2,
    },
    {
      id: 2,
      source: "Walk-in",
      projectId: resolvedProjectId,
      rmId: resolvedRms[1 % rmCount] || 1,
      emId: 2,
      count: 840,
      quantityDistribution: 35,
      conversionRate: 8.4,
      junkRate: 8.2,
    },
    {
      id: 3,
      source: "Google Ads",
      projectId: resolvedProjectId,
      rmId: resolvedRms[2 % rmCount] || 1,
      emId: 1,
      count: 2245,
      quantityDistribution: 82,
      conversionRate: 12.6,
      junkRate: 8.2,
    },
    {
      id: 4,
      source: "Referrals",
      projectId: resolvedProjectId,
      rmId: resolvedRms[3 % rmCount] || 1,
      emId: 3,
      count: 632,
      quantityDistribution: 29,
      conversionRate: 2.5,
      junkRate: 8.2,
    },
    {
      id: 5,
      source: "Facebook Ads",
      projectId: resolvedProjectId === 1 ? 2 : resolvedProjectId,
      rmId: resolvedRms[4 % rmCount] || 1,
      emId: 2,
      count: 1120,
      quantityDistribution: 42,
      conversionRate: 6.8,
      junkRate: 10.5,
    },
    {
      id: 6,
      source: "Meta Lead Forms",
      projectId: resolvedProjectId,
      rmId: resolvedRms[5 % rmCount] || 1,
      emId: 1,
      count: 1530,
      quantityDistribution: 55,
      conversionRate: 9.1,
      junkRate: 12.4,
    },
    {
      id: 7,
      source: "Website Direct",
      projectId: resolvedProjectId,
      rmId: resolvedRms[6 % rmCount] || 1,
      emId: 4,
      count: 940,
      quantityDistribution: 38,
      conversionRate: 11.2,
      junkRate: 5.1,
    },
    {
      id: 8,
      source: "Property Portals",
      projectId: resolvedProjectId === 1 ? 2 : resolvedProjectId,
      rmId: resolvedRms[7 % rmCount] || 1,
      emId: 3,
      count: 1890,
      quantityDistribution: 68,
      conversionRate: 5.4,
      junkRate: 14.8,
    },
    {
      id: 9,
      source: "Email Campaigns",
      projectId: resolvedProjectId,
      rmId: resolvedRms[8 % rmCount] || 1,
      emId: 2,
      count: 420,
      quantityDistribution: 18,
      conversionRate: 3.2,
      junkRate: 9.3,
    },
    {
      id: 10,
      source: "SMS Campaigns",
      projectId: resolvedProjectId,
      rmId: resolvedRms[9 % rmCount] || 1,
      emId: 1,
      count: 310,
      quantityDistribution: 12,
      conversionRate: 1.8,
      junkRate: 18.2,
    },
    {
      id: 11,
      source: "Real Estate Agents",
      projectId: resolvedProjectId,
      rmId: resolvedRms[10 % rmCount] || 1,
      emId: 4,
      count: 780,
      quantityDistribution: 32,
      conversionRate: 14.2,
      junkRate: 6.2,
    },
    {
      id: 12,
      source: "Outdoor Billboards",
      projectId: resolvedProjectId === 1 ? 2 : resolvedProjectId,
      rmId: resolvedRms[11 % rmCount] || 1,
      emId: 3,
      count: 210,
      quantityDistribution: 8,
      conversionRate: 0.9,
      junkRate: 4.5,
    },
  ];
};
