import type { PersonaSegmentRow, VolumeMetric } from "../types";

export const occupationData: VolumeMetric[] = [
  { label: "Software Engineering", value: 42 },
  { label: "Business / Consulting", value: 28 },
  { label: "Medical Professional", value: 18 },
  { label: "Others", value: 12 },
];

export const ageData: VolumeMetric[] = [
  { label: "20-40", value: 45 },
  { label: "40-60", value: 32 },
  { label: "60-80", value: 15 },
  { label: "Others", value: 8 },
];

export const stateData: VolumeMetric[] = [
  { label: "Telangana", value: 1248 },
  { label: "Andhra Pradesh", value: 952 },
  { label: "Karnataka", value: 810 },
  { label: "Others", value: 680 },
];

export const getInitialPersonaData = (
  resolvedProjectId: number,
  resolvedRms: number[]
): PersonaSegmentRow[] => {
  const firstRmId = resolvedRms[0] || 1;
  const secondRmId = resolvedRms[1] || 2;
  const thirdRmId = resolvedRms[2] || 3;

  return [
    {
      id: 1,
      name: "Young Professional",
      projectId: resolvedProjectId,
      projectName: "Planet Green",
      rmId: firstRmId,
      emId: 10,
      topObjections: ["Budget", "EMI"],
      avgIncome: "₹42L+",
      junkRate: 14.2,
      conversionRate: 4.2,
    },
    {
      id: 2,
      name: "Tech Entrepreneur",
      projectId: resolvedProjectId,
      projectName: "Planet Green",
      rmId: firstRmId,
      emId: 11,
      topObjections: ["Location", "Smart Home"],
      avgIncome: "₹50L+",
      junkRate: 8.5,
      conversionRate: 6.8,
    },
    {
      id: 3,
      name: "Senior Executive",
      projectId: resolvedProjectId,
      projectName: "Planet Green",
      rmId: secondRmId,
      emId: 12,
      topObjections: ["Privacy", "Legacy"],
      avgIncome: "₹1.2Cr+",
      junkRate: 5.1,
      conversionRate: 9.4,
    },
    {
      id: 4,
      name: "NRI Investor",
      projectId: resolvedProjectId,
      projectName: "Planet Green",
      rmId: secondRmId,
      emId: 13,
      topObjections: ["ROI", "Maintenance"],
      avgIncome: "₹72L+",
      junkRate: 22.4,
      conversionRate: 2.1,
    },
    {
      id: 5,
      name: "Creative Professional",
      projectId: resolvedProjectId,
      projectName: "Planet Green",
      rmId: thirdRmId,
      emId: 14,
      topObjections: ["Vastu", "Amenities"],
      avgIncome: "₹35L+",
      junkRate: 12.0,
      conversionRate: 5.5,
    },
    {
      id: 6,
      name: "Startup Founder",
      projectId: resolvedProjectId,
      projectName: "Planet Green",
      rmId: thirdRmId,
      emId: 15,
      topObjections: ["Timeline", "Flexibility"],
      avgIncome: "₹90L+",
      junkRate: 9.2,
      conversionRate: 7.5,
    },
    {
      id: 7,
      name: "Retiring Couple",
      projectId: resolvedProjectId,
      projectName: "Planet Green",
      rmId: firstRmId,
      emId: 10,
      topObjections: ["Accessibility", "Security"],
      avgIncome: "₹60L+",
      junkRate: 6.4,
      conversionRate: 8.0,
    },
    {
      id: 8,
      name: "Medical Specialist",
      projectId: resolvedProjectId,
      projectName: "Planet Green",
      rmId: secondRmId,
      emId: 12,
      topObjections: ["Parking", "Proximity"],
      avgIncome: "₹1.5Cr+",
      junkRate: 4.8,
      conversionRate: 10.2,
    },
    {
      id: 9,
      name: "Government Employee",
      projectId: resolvedProjectId,
      projectName: "Planet Green",
      rmId: thirdRmId,
      emId: 14,
      topObjections: ["LTC Approval", "Budget"],
      avgIncome: "₹28L+",
      junkRate: 15.1,
      conversionRate: 3.5,
    },
    {
      id: 10,
      name: "Business Owner",
      projectId: resolvedProjectId,
      projectName: "Planet Green",
      rmId: firstRmId,
      emId: 11,
      topObjections: ["GST Benefit", "Commercial Zone"],
      avgIncome: "₹85L+",
      junkRate: 7.8,
      conversionRate: 6.0,
    },
    {
      id: 11,
      name: "IT Manager",
      projectId: resolvedProjectId,
      projectName: "Planet Green",
      rmId: secondRmId,
      emId: 13,
      topObjections: ["Connectivity", "Power Backup"],
      avgIncome: "₹48L+",
      junkRate: 11.5,
      conversionRate: 5.0,
    },
    {
      id: 12,
      name: "Agriculture Magnate",
      projectId: resolvedProjectId,
      projectName: "Planet Green",
      rmId: thirdRmId,
      emId: 15,
      topObjections: ["Land Title", "Water Source"],
      avgIncome: "₹1.1Cr+",
      junkRate: 18.2,
      conversionRate: 4.5,
    },
  ];
};
